const books = [
  {
    id: 1,
    name: "Book 1",
    genre: "Action",
    status: "Published",
    created: "2020-01-01",
  },
  {
    id: 2,
    name: "Book 2",
    genre: "Drama",
    status: "Not Published",
    created: "2020-01-01",
  },
  {
    id: 3,
    name: "Book 3",
    genre: "Comedy",
    status: "Published",
    created: "2020-01-03",
  },
  {
    id: 4,
    name: "Book 4",
    genre: "Drama",
    status: "Not Published",
    created: "2020-01-07",
  },
  {
    id: 5,
    name: "Book 5",
    genre: "Thriller",
    status: "Published",
    created: "2020-01-05",
  },
  {
    id: 6,
    name: "Book 1",
    genre: "Sci-Fi",
    status: "Not Published",
    created: "2020-01-05",
  },
  {
    id: 7,
    name: "Book 7",
    genre: "Romance",
    status: "Published",
    created: "2020-01-03",
  },
  {
    id: 8,
    name: "Book 8",
    genre: "Mystery",
    status: "Not Published",
    created: "2020-01-01",
  },
  {
    id: 9,
    name: "Book 9",
    genre: "Action",
    status: "Published",
    created: "2020-01-02",
  },
  {
    id: 10,
    name: "Book 10",
    genre: "Drama",
    status: "Not Published",
    created: "2020-01-02",
  },
  {
    id: 11,
    name: "Book 11",
    genre: "Action",
    status: "Published",
    created: "2020-01-01",
  },
  {
    id: 12,
    name: "Book 12",
    genre: "Comedy",
    status: "Not Published",
    created: "2020-01-01",
  },
  {
    id: 13,
    name: "Book 13",
    genre: "Horror",
    status: "Published",
    created: "2020-01-03",
  },
  {
    id: 14,
    name: "Book 14",
    genre: "Sci-Fi",
    status: "Not Published",
    created: "2020-01-07",
  },
  {
    id: 15,
    name: "Book 15",
    genre: "Thriller",
    status: "Published",
    created: "2020-01-05",
  },
  {
    id: 16,
    name: "Book 16",
    genre: "Romance",
    status: "Not Published",
    created: "2020-01-05",
  },
  {
    id: 17,
    name: "Book 17",
    genre: "Mystery",
    status: "Published",
    created: "2020-01-03",
  },
  {
    id: 18,
    name: "Book 18",
    genre: "Mystery",
    status: "Not Published",
    created: "2020-01-01",
  },
  {
    id: 19,
    name: "Book 19",
    genre: "Action",
    status: "Published",
    created: "2020-01-02",
  },
  {
    id: 20,
    name: "Book 20",
    genre: "Horror",
    status: "Not Published",
    created: "2020-01-02",
  },
];

module.exports = books;
